# Generated by Django 2.1.7 on 2019-03-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20190314_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='vaild_from',
            new_name='valid_from',
        ),
    ]
